### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by aman400** [BranchMetrics/Branch-Android-SDK#68]
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
       at io.branch.referral.ServerRequestQueue.containsClose(ServerRequestQueue.java:159)
       at io.branch.referral.Branch$6.run(Branch.java:452)
       at java.lang.Thread.run(Thread.java:818)

**Comment by aaustin** [comment]
@aman400 I'm so sorry you were affected by this. We fixed this in v 1.5.1 of the SDK. Please update at your earliest convenience.

It was a rare synchronization issue that our tests didn't catch unfortunately. Hopefully the impact was minimal.

**Comment by peymankh** [comment]
Hi @aaustin, This issue is still happening in 1.5.4.
![screen shot 2015-05-15 at 11 05 40](https://cloud.githubusercontent.com/assets/1993704/7650844/6089d774-faf2-11e4-95aa-8c51f57ea4cf.png)

**Comment by peymankh** [comment]
On a different side, might have been fixed in V 1.5.5. according to their changelog.
Which has exactly addressed this crash.

![screen shot 2015-05-15 at 11 08 17](https://cloud.githubusercontent.com/assets/1993704/7650886/c3bc321a-faf2-11e4-9cb8-fe5ff8345202.png)

**Comment by aaustin** [comment]
I'm so sorry @peymankh. You're right but we did find a fix. These multithreaded bugs are so hard to test for screen out of production, but I think we're in the clear now. This was actually the same bug as the previous reported, but our previous fix wasn't thorough enough.

It's now been resolved. I'm really sorry about it!

**Comment by peymankh** [comment]
@aaustin Thanks for the reply. Looking at the changelog of v1.5.5, seems to me that this issue has been addressed. I guess what I do is update to that version for the time being and see if the issue has been resolved.

**Comment by sojanpr** [comment]
@peymankh We have released v1.6.0 with lot of enhancement on thread handling. So the concurrent modification issues should not happen any more. Please update  to v1.6.0
